name: github-action
env:
  testID: "14630762"
  continuePipeline: "false"
  showTailLog: "false"
  
on: push
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run Blazemeter test
        uses: BlazeRunner-BZR/Github-Action@v8.4
        id: run-test
        with:
          apiKey: ${{ secrets.BLAZEMETER_API_KEY }}
          apiSecret: ${{ secrets.BLAZEMETER_API_SECRET }}
          testID: ${{env.testID}}
          continuePipeline: ${{env.continuePipeline}}
          showTailLog: ${{env.showTailLog}}
